Repository FoKE-Developers/FourCutTogether, pull requests merged in 2024-10, with the labels that each got.

#50 modify base design code [#32]
  app/src/main/AndroidManifest.xml
  presenter/src/main/java/com/foke/together/presenter/MainActivity.kt
  presenter/src/main/java/com/foke/together/presenter/frame/FourCutFrame.kt
  presenter/src/main/java/com/foke/together/presenter/frame/MakerFaireFrame.kt
  presenter/src/main/java/com/foke/together/presenter/navigation/NavGraph.kt
  presenter/src/main/java/com/foke/together/presenter/screen/CameraScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/HomeScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/SelectFrameScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/SelectMethodScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/ShareScreen.kt
  presenter/src/main/java/com/foke/together/presenter/theme/Color.kt
  presenter/src/main/java/com/foke/together/presenter/theme/Shape.kt
  presenter/src/main/java/com/foke/together/presenter/theme/Theme.kt
  presenter/src/main/java/com/foke/together/presenter/theme/Type.kt
  presenter/src/main/java/com/foke/together/presenter/ui/theme/Type.kt
  presenter/src/main/res/drawable/maker_faire_frame.png
  presenter/src/main/res/values/colors.xml
  presenter/src/main/res/values/theme_overlays.xml
  presenter/src/main/res/values/themes.xml
  util/src/main/java/com/foke/together/util/TimeUtil.kt
Labels: New Implementation, feature/UI

#52 add usecase to set camera source type [#32]
  data/src/main/java/com/foke/together/data/repository/AppPreferencesRepository.kt
  data/src/main/proto/app_preferences.proto
  domain/src/main/java/com/foke/together/domain/input/GetCameraSourceTypeInterface.kt
  domain/src/main/java/com/foke/together/domain/input/GetSampleDataInterface.kt
  domain/src/main/java/com/foke/together/domain/interactor/GetCameraSourceTypeUseCase.kt
  domain/src/main/java/com/foke/together/domain/interactor/GetSampleDataUseCase.kt
  domain/src/main/java/com/foke/together/domain/output/AppPreferenceInterface.kt
Labels: New Implementation, feature/structure

#56 add CountDownTimer in CameraViewmodel #9
  presenter/src/main/java/com/foke/together/presenter/screen/CameraScreen.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/CameraViewModel.kt
Labels: New Implementation, feature/UI

#62 remove input interface [#61]
  domain/src/main/java/com/foke/together/domain/input/GetCameraSourceTypeInterface.kt
  domain/src/main/java/com/foke/together/domain/input/GetExternalCameraIPInterface.kt
  domain/src/main/java/com/foke/together/domain/input/SetCameraSourceTypeInterface.kt
  domain/src/main/java/com/foke/together/domain/input/SetExternalCameraIPInterface.kt
  domain/src/main/java/com/foke/together/domain/input/di/UseCaseModule.kt
  domain/src/main/java/com/foke/together/domain/interactor/GetCameraSourceTypeUseCase.kt
  domain/src/main/java/com/foke/together/domain/interactor/GetExternalCameraIPUseCase.kt
  domain/src/main/java/com/foke/together/domain/interactor/SetCameraSourceTypeUseCase.kt
  domain/src/main/java/com/foke/together/domain/interactor/SetExternalCameraIPUseCase.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/SettingViewModel.kt
Labels: bug, feature/structure

#69 add AndroidCameraDataSource [#58]
  external/src/main/java/com/foke/together/external/local/AndroidCameraDataSource.kt
Labels: New Implementation, feature/external

#74 Generate Image [#59]
  domain/src/main/java/com/foke/together/domain/interactor/CaptureWithExternalCameraUseCase.kt
  domain/src/main/java/com/foke/together/domain/interactor/GeneratePhotoFrameUseCase.kt
  domain/src/main/java/com/foke/together/domain/interactor/entity/CutFrameType.kt
  domain/src/main/java/com/foke/together/domain/output/ImageRepositoryInterface.kt
  external/src/main/java/com/foke/together/external/repository/ImageRepository.kt
  external/src/main/java/com/foke/together/external/repository/di/RepositoryModule.kt
  gradle/libs.versions.toml
  presenter/build.gradle.kts
  presenter/src/main/java/com/foke/together/presenter/frame/FourCutFrame.kt
  presenter/src/main/java/com/foke/together/presenter/frame/MakerFaireFrame.kt
  presenter/src/main/java/com/foke/together/presenter/navigation/NavGraph.kt
  presenter/src/main/java/com/foke/together/presenter/navigation/NavRoute.kt
  presenter/src/main/java/com/foke/together/presenter/screen/CameraScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/GenerateSingleRowImageScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/GenerateTwoRowImageScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/SelectFrameScreen.kt
  presenter/src/main/java/com/foke/together/presenter/screen/ShareScreen.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/CameraViewModel.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/GenerateSingleRowImageViewModel.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/GenerateTwoRowImageViewModel.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/SelectFrameViewModel.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/ShareViewModel.kt
  util/src/main/java/com/foke/together/util/AppPolicy.kt
  util/src/main/java/com/foke/together/util/ImageFileUtil.kt
Labels: feature/UI, feature/external, feature/etc

#86 update dependency versions [#85]
  gradle/libs.versions.toml
Labels: bug

#87 Bug fix. get and set ip address [#28]
  domain/src/main/java/com/foke/together/domain/interactor/AppInitUseCase.kt
  presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/HomeViewModel.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/SettingViewModel.kt
Labels: bug

#88 fix home screen design [#27]
  presenter/src/main/java/com/foke/together/presenter/screen/HomeScreen.kt
  presenter/src/main/res/drawable/fourcut_together.xml
  presenter/src/main/res/values/colors.xml
  presenter/src/main/res/values/strings.xml
Labels: bug

#91 do some chores [#85]
  data/src/main/java/com/foke/together/data/datasource/local/datastore/AppPreferencesSerializer.kt
  presenter/src/main/res/values/strings.xml
  util/src/main/java/com/foke/together/util/AppPolicy.kt
  util/src/main/java/com/foke/together/util/TimeUtil.kt
Labels: bug

#92 add network debug logs [#85]
  external/src/main/java/com/foke/together/external/camera/external/interceptor/BaseUrlInterceptor.kt
  util/src/main/java/com/foke/together/util/retrofit/NetworkCall.kt
Labels: bug

#93 fix select frame screen [#30]
  presenter/src/main/java/com/foke/together/presenter/screen/SelectFrameScreen.kt
Labels: bug

#95 fix select method screen [#43]
  presenter/src/main/java/com/foke/together/presenter/screen/SelectMethodScreen.kt
Labels: bug, feature/UI

#98 bug fix. net work logger block communications [#85]
  util/src/main/java/com/foke/together/util/retrofit/NetworkCall.kt
Labels: bug

#99 bug fix. getCurrentUserInformationUseCase return nothings [#85]
  domain/src/main/java/com/foke/together/domain/interactor/web/GetDownloadUrlUseCase.kt
Labels: bug, feature/external

#100 hotfix. display qr code in share screen [#90]
  presenter/src/main/java/com/foke/together/presenter/screen/ShareScreen.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/ShareViewModel.kt
Labels: bug, feature/UI

#97 feat: add setting screen elements [#28]
  presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt
Labels: New Implementation, feature/UI

#101 fix camera screen [#29]
  presenter/src/main/java/com/foke/together/presenter/screen/CameraScreen.kt
Labels: bug, feature/UI

#104 hotfix. take photo with external camera [#89]
  domain/src/main/java/com/foke/together/domain/interactor/CaptureWithExternalCameraUseCase.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/CameraViewModel.kt
Labels: bug, feature/external

#105 feat: add capture interval input [#28]
  presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt
Labels: New Implementation, feature/UI

#106 hotfix. fix wrong cut frame color [#103]
  presenter/src/main/java/com/foke/together/presenter/screen/GenerateTwoRowImageScreen.kt
Labels: bug

#107 disable un-implemented code and do some chore [#85]
  presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt
  presenter/src/main/java/com/foke/together/presenter/viewmodel/SettingViewModel.kt
Labels: bug

#108 version up to v1.0.0 [#85]
  gradle/libs.versions.toml
  util/src/main/java/com/foke/together/util/AppPolicy.kt
Labels: New Implementation
